name: 'composite-mssql-deploy-dbup'
description: 'Render variables, substitute variables and invoke DbUp executable'
inputs:
  dotnetVersion:
    description: 'dotNet version. E.g. 6.0.x'
    required: true
  publishPath:
    description: 'publishing path of the binaries'
    required: true
  environment: 
    description: 'Target environment to deploy to'
    required: true
  variableFile: 
    description: 'json file with variables for rendering with json-variables'
    required: true
  secrets:
    description: 'serialized json string for github secrets'
    required: true
  configurationFile:
    description: 'configuration file to perform variable substitution'
    required: true
  dbUpExecutable:
    description: 'Full path to dbUp executable. E.g. ./src/dbup/bin/relase/dbup.exe'
    required: true

  
  
outputs:
  random-number:
    description: "Random number"
    value: ${{ steps.random-number-generator.outputs.random-id }}
    
runs:
  using: "composite"
  steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
         dotnet-version: 6.0.x

      - name: Set environment specific variables
        uses: jnus/json-variables@4d729bb7248e73b81440da6bee6824e6102d775c
        with:
          scope: ${{inputs.environment}}
          configFile: '${{inputs.variableFile}}'
          secrets: '${{ inputs.secrets }}'

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{inputs.configurationFile}}'

      - name: Execute DbUp
        run: dotnet src/orbit.DbUp/bin/Debug/net6.0/orbit.DbUp.dll
        shell: pwsh